const en = {
  'opm.phase.planned': 'Planned',
  'opm.phase.active': 'Working',
  'opm.phase.waitingOwner': 'Waiting on you',
  'opm.phase.waiting': 'Waiting',
  'opm.phase.paused': 'Paused',
  'opm.phase.blocked': 'Blocked',
  'opm.phase.review': 'In review',
  'opm.phase.merged': 'Merged',
  'opm.phase.deployed': 'Deployed',
  'opm.phase.verified': 'Verified',
  'opm.phase.completed': 'Completed',
  'opm.phase.cancelled': 'Cancelled',
  'opm.phase.failed': 'Failed',
  'opm.phase.idle': 'Idle',
  'opm.owner.authorize': 'You need to act. Post the command below on issue #{ref} to approve the protected change.',
  'opm.owner.deadLetter': 'You need to act. Fix the repeated failure, then comment "/agent resume" on issue #{ref}.',
  'opm.owner.paused': 'You paused this. Comment "/agent resume" on issue #{ref} to continue.',
  'opm.owner.children': 'Nothing needed from you. This parent finishes when its child items finish.',
  'opm.owner.review': 'Nothing needed from you. OPM dispatches a reviewer and continues after the verdict.',
  'opm.owner.checks': 'Nothing needed from you. CI is running on the candidate.',
  'opm.owner.deployment': 'Nothing needed from you. The merge is deploying.',
  'opm.owner.worker': 'Nothing needed from you. Work starts when a worker slot is free.',
  'opm.owner.working': 'Nothing needed from you. OPM is working on it.',
  'opm.owner.nextAction': 'Nothing obvious for you. OPM says: {action}',
  'opm.owner.none': 'Nothing needed from you right now.',
  'opm.row.childOf': 'child of #{ref}',
  'opm.row.nextAction': 'Next: {action}',
  'opm.row.branch': 'branch {branch}',
  'opm.row.session': 'session {session}',
  'opm.row.effect': 'effect {kind}: {status}',
  'opm.actions.copy': 'Copy',
  'opm.actions.copied': 'Copied',
  'opm.actions.run': 'Run',
  'opm.actions.running': 'Sending…',
  'opm.actions.sent': 'Sent ✓',
  'opm.actions.openSession': 'Open session',
  'opm.actions.enableNotifications': 'Enable notifications',
  'opm.supervisor.title': 'OPM supervisor status',
  'opm.supervisor.running': 'Running',
  'opm.supervisor.stopped': 'Stopped',
  'opm.supervisor.paused': 'Paused',
  'opm.supervisor.lastPoll': 'Last poll {age}',
  'opm.supervisor.deadLetters': 'Dead letters: {count}',
  'opm.supervisor.blocked': 'Blocked: {count}',
  'opm.supervisor.degraded': 'Degraded',
  'opm.supervisor.rateLimited': 'Rate limited',
  'opm.supervisor.healthy': 'Healthy',
  'opm.notification.title': 'OPM needs your action',
  'opm.notification.body': '{item}',
  'opm.pill.offline': 'OPM offline',
  'opm.pill.needsYou': 'OPM · needs you ({count})',
  'opm.pill.blocked': 'OPM · blocked ({count})',
  'opm.pill.working': 'OPM · working ({count})',
  'opm.pill.waiting': 'OPM · waiting ({count})',
  'opm.pill.queued': 'OPM · queued ({count})',
  'opm.pill.idle': 'OPM · idle',
  'opm.pill.aria': 'Open OPM status',
  'opm.dialog.noSummary': 'No summary',
  'opm.dialog.updated': 'Updated {age}',
  'opm.dialog.unavailable': 'OPM status is unavailable',
  'opm.dialog.controlUnreachable': 'The OPM control server cannot be reached. This is unavailable state, not an empty work list.',
  'opm.section.needsYou': 'Needs you ({count})',
  'opm.section.workItems': 'Work items',
  'opm.section.empty': 'No work items in flight.',
  'opm.footer.counts': 'Needs you {needsYou} · blocked {blocked} · working {working} · waiting {waiting} · queued {queued}',
};

type OpmMessages = Record<keyof typeof en, string>;

const de = {
  'opm.phase.planned': 'Geplant', 'opm.phase.active': 'In Arbeit', 'opm.phase.waitingOwner': 'Wartet auf dich', 'opm.phase.waiting': 'Wartet', 'opm.phase.paused': 'Pausiert', 'opm.phase.blocked': 'Blockiert', 'opm.phase.review': 'In Prüfung', 'opm.phase.merged': 'Zusammengeführt', 'opm.phase.deployed': 'Bereitgestellt', 'opm.phase.verified': 'Verifiziert', 'opm.phase.completed': 'Abgeschlossen', 'opm.phase.cancelled': 'Abgebrochen', 'opm.phase.failed': 'Fehlgeschlagen', 'opm.phase.idle': 'Inaktiv',
  'opm.owner.authorize': 'Du musst handeln. Sende den Befehl unten in Issue #{ref}, um die geschützte Änderung zu genehmigen.', 'opm.owner.deadLetter': 'Du musst handeln. Behebe den wiederholten Fehler und kommentiere dann "/agent resume" in Issue #{ref}.', 'opm.owner.paused': 'Du hast dies pausiert. Kommentiere "/agent resume" in Issue #{ref}, um fortzufahren.', 'opm.owner.children': 'Du musst nichts tun. Dieses übergeordnete Element wird abgeschlossen, wenn seine untergeordneten Elemente fertig sind.', 'opm.owner.review': 'Du musst nichts tun. OPM beauftragt eine Prüfung und fährt nach dem Urteil fort.', 'opm.owner.checks': 'Du musst nichts tun. CI prüft den Kandidaten.', 'opm.owner.deployment': 'Du musst nichts tun. Der Merge wird bereitgestellt.', 'opm.owner.worker': 'Du musst nichts tun. Die Arbeit beginnt, sobald ein Worker-Platz frei ist.', 'opm.owner.working': 'Du musst nichts tun. OPM arbeitet daran.', 'opm.owner.nextAction': 'Für dich ist keine klare Aktion nötig. OPM sagt: {action}', 'opm.owner.none': 'Du musst im Moment nichts tun.',
  'opm.row.childOf': 'untergeordnet zu #{ref}', 'opm.row.nextAction': 'Als Nächstes: {action}', 'opm.row.branch': 'Branch {branch}', 'opm.row.session': 'Sitzung {session}', 'opm.row.effect': 'Effekt {kind}: {status}', 'opm.actions.copy': 'Kopieren', 'opm.actions.copied': 'Kopiert', 'opm.actions.run': 'Ausführen', 'opm.actions.running': 'Wird gesendet…', 'opm.actions.sent': 'Gesendet ✓', 'opm.actions.openSession': 'Sitzung öffnen', 'opm.actions.enableNotifications': 'Benachrichtigungen aktivieren',
  'opm.supervisor.title': 'OPM-Supervisorstatus', 'opm.supervisor.running': 'Läuft', 'opm.supervisor.stopped': 'Gestoppt', 'opm.supervisor.paused': 'Pausiert', 'opm.supervisor.lastPoll': 'Letzte Abfrage {age}', 'opm.supervisor.deadLetters': 'Nicht zustellbar: {count}', 'opm.supervisor.blocked': 'Blockiert: {count}', 'opm.supervisor.degraded': 'Beeinträchtigt', 'opm.supervisor.rateLimited': 'Rate-Limit erreicht', 'opm.supervisor.healthy': 'Fehlerfrei',
  'opm.notification.title': 'OPM benötigt deine Aktion', 'opm.notification.body': '{item}', 'opm.pill.offline': 'OPM offline', 'opm.pill.needsYou': 'OPM · du bist gefragt ({count})', 'opm.pill.blocked': 'OPM · blockiert ({count})', 'opm.pill.working': 'OPM · in Arbeit ({count})', 'opm.pill.waiting': 'OPM · wartet ({count})', 'opm.pill.queued': 'OPM · eingereiht ({count})', 'opm.pill.idle': 'OPM · inaktiv', 'opm.pill.aria': 'OPM-Status öffnen',
  'opm.dialog.noSummary': 'Keine Zusammenfassung', 'opm.dialog.updated': 'Aktualisiert {age}', 'opm.dialog.unavailable': 'OPM-Status ist nicht verfügbar', 'opm.dialog.controlUnreachable': 'Der OPM-Steuerungsserver ist nicht erreichbar. Dies ist ein Nichtverfügbarkeitszustand, keine leere Arbeitsliste.', 'opm.section.needsYou': 'Du bist gefragt ({count})', 'opm.section.workItems': 'Arbeitselemente', 'opm.section.empty': 'Keine laufenden Arbeitselemente.', 'opm.footer.counts': 'Du bist gefragt {needsYou} · blockiert {blocked} · in Arbeit {working} · wartend {waiting} · eingereiht {queued}',
} satisfies OpmMessages;

const es = {
  'opm.phase.planned': 'Planificado', 'opm.phase.active': 'En curso', 'opm.phase.waitingOwner': 'Esperando tu acción', 'opm.phase.waiting': 'En espera', 'opm.phase.paused': 'Pausado', 'opm.phase.blocked': 'Bloqueado', 'opm.phase.review': 'En revisión', 'opm.phase.merged': 'Fusionado', 'opm.phase.deployed': 'Desplegado', 'opm.phase.verified': 'Verificado', 'opm.phase.completed': 'Completado', 'opm.phase.cancelled': 'Cancelado', 'opm.phase.failed': 'Fallido', 'opm.phase.idle': 'Inactivo',
  'opm.owner.authorize': 'Debes actuar. Publica el comando de abajo en la incidencia #{ref} para aprobar el cambio protegido.', 'opm.owner.deadLetter': 'Debes actuar. Corrige el fallo repetido y comenta "/agent resume" en la incidencia #{ref}.', 'opm.owner.paused': 'Tú pausaste esto. Comenta "/agent resume" en la incidencia #{ref} para continuar.', 'opm.owner.children': 'No necesitas hacer nada. Este elemento principal termina cuando terminan sus elementos secundarios.', 'opm.owner.review': 'No necesitas hacer nada. OPM asigna una revisión y continúa tras el veredicto.', 'opm.owner.checks': 'No necesitas hacer nada. CI está comprobando el candidato.', 'opm.owner.deployment': 'No necesitas hacer nada. La fusión se está desplegando.', 'opm.owner.worker': 'No necesitas hacer nada. El trabajo comienza cuando queda libre un puesto de ejecución.', 'opm.owner.working': 'No necesitas hacer nada. OPM está trabajando en ello.', 'opm.owner.nextAction': 'No hay una acción clara para ti. OPM indica: {action}', 'opm.owner.none': 'No necesitas hacer nada ahora.',
  'opm.row.childOf': 'secundario de #{ref}', 'opm.row.nextAction': 'Siguiente: {action}', 'opm.row.branch': 'rama {branch}', 'opm.row.session': 'sesión {session}', 'opm.row.effect': 'efecto {kind}: {status}', 'opm.actions.copy': 'Copiar', 'opm.actions.copied': 'Copiado', 'opm.actions.run': 'Ejecutar', 'opm.actions.running': 'Enviando…', 'opm.actions.sent': 'Enviado ✓', 'opm.actions.openSession': 'Abrir sesión', 'opm.actions.enableNotifications': 'Activar notificaciones',
  'opm.supervisor.title': 'Estado del supervisor de OPM', 'opm.supervisor.running': 'En ejecución', 'opm.supervisor.stopped': 'Detenido', 'opm.supervisor.paused': 'Pausado', 'opm.supervisor.lastPoll': 'Última consulta {age}', 'opm.supervisor.deadLetters': 'Mensajes fallidos: {count}', 'opm.supervisor.blocked': 'Bloqueados: {count}', 'opm.supervisor.degraded': 'Degradado', 'opm.supervisor.rateLimited': 'Límite de frecuencia alcanzado', 'opm.supervisor.healthy': 'Correcto',
  'opm.notification.title': 'OPM necesita tu acción', 'opm.notification.body': '{item}', 'opm.pill.offline': 'OPM sin conexión', 'opm.pill.needsYou': 'OPM · te necesita ({count})', 'opm.pill.blocked': 'OPM · bloqueado ({count})', 'opm.pill.working': 'OPM · en curso ({count})', 'opm.pill.waiting': 'OPM · en espera ({count})', 'opm.pill.queued': 'OPM · en cola ({count})', 'opm.pill.idle': 'OPM · inactivo', 'opm.pill.aria': 'Abrir estado de OPM',
  'opm.dialog.noSummary': 'Sin resumen', 'opm.dialog.updated': 'Actualizado {age}', 'opm.dialog.unavailable': 'El estado de OPM no está disponible', 'opm.dialog.controlUnreachable': 'No se puede acceder al servidor de control de OPM. Este estado indica que no está disponible, no que la lista de trabajo esté vacía.', 'opm.section.needsYou': 'Necesita tu acción ({count})', 'opm.section.workItems': 'Elementos de trabajo', 'opm.section.empty': 'No hay elementos de trabajo en curso.', 'opm.footer.counts': 'Tu acción {needsYou} · bloqueados {blocked} · en curso {working} · en espera {waiting} · en cola {queued}',
} satisfies OpmMessages;

const fr = {
  'opm.phase.planned': 'Planifié', 'opm.phase.active': 'En cours', 'opm.phase.waitingOwner': 'Attend votre action', 'opm.phase.waiting': 'En attente', 'opm.phase.paused': 'En pause', 'opm.phase.blocked': 'Bloqué', 'opm.phase.review': 'En révision', 'opm.phase.merged': 'Fusionné', 'opm.phase.deployed': 'Déployé', 'opm.phase.verified': 'Vérifié', 'opm.phase.completed': 'Terminé', 'opm.phase.cancelled': 'Annulé', 'opm.phase.failed': 'Échoué', 'opm.phase.idle': 'Inactif',
  'opm.owner.authorize': 'Vous devez agir. Publiez la commande ci-dessous sur le ticket nº {ref} pour approuver la modification protégée.', 'opm.owner.deadLetter': 'Vous devez agir. Corrigez l’échec répété, puis commentez "/agent resume" sur le ticket nº {ref}.', 'opm.owner.paused': 'Vous avez mis cet élément en pause. Commentez "/agent resume" sur le ticket nº {ref} pour continuer.', 'opm.owner.children': 'Aucune action requise. Cet élément parent se termine lorsque ses éléments enfants sont terminés.', 'opm.owner.review': 'Aucune action requise. OPM lance une révision et poursuit après le verdict.', 'opm.owner.checks': 'Aucune action requise. La CI vérifie le candidat.', 'opm.owner.deployment': 'Aucune action requise. La fusion est en cours de déploiement.', 'opm.owner.worker': 'Aucune action requise. Le travail commence lorsqu’une place d’exécution se libère.', 'opm.owner.working': 'Aucune action requise. OPM travaille dessus.', 'opm.owner.nextAction': 'Aucune action évidente pour vous. OPM indique : {action}', 'opm.owner.none': 'Aucune action requise pour le moment.',
  'opm.row.childOf': 'enfant de nº {ref}', 'opm.row.nextAction': 'Suite : {action}', 'opm.row.branch': 'branche {branch}', 'opm.row.session': 'session {session}', 'opm.row.effect': 'effet {kind} : {status}', 'opm.actions.copy': 'Copier', 'opm.actions.copied': 'Copié', 'opm.actions.run': 'Exécuter', 'opm.actions.running': 'Envoi…', 'opm.actions.sent': 'Envoyé ✓', 'opm.actions.openSession': 'Ouvrir la session', 'opm.actions.enableNotifications': 'Activer les notifications',
  'opm.supervisor.title': 'État du superviseur OPM', 'opm.supervisor.running': 'En cours', 'opm.supervisor.stopped': 'Arrêté', 'opm.supervisor.paused': 'En pause', 'opm.supervisor.lastPoll': 'Dernière interrogation {age}', 'opm.supervisor.deadLetters': 'Messages en échec : {count}', 'opm.supervisor.blocked': 'Bloqués : {count}', 'opm.supervisor.degraded': 'Dégradé', 'opm.supervisor.rateLimited': 'Débit limité', 'opm.supervisor.healthy': 'Sain',
  'opm.notification.title': 'OPM attend votre action', 'opm.notification.body': '{item}', 'opm.pill.offline': 'OPM hors ligne', 'opm.pill.needsYou': 'OPM · votre action ({count})', 'opm.pill.blocked': 'OPM · bloqué ({count})', 'opm.pill.working': 'OPM · en cours ({count})', 'opm.pill.waiting': 'OPM · en attente ({count})', 'opm.pill.queued': 'OPM · en file ({count})', 'opm.pill.idle': 'OPM · inactif', 'opm.pill.aria': 'Ouvrir l’état OPM',
  'opm.dialog.noSummary': 'Aucun résumé', 'opm.dialog.updated': 'Mis à jour {age}', 'opm.dialog.unavailable': 'L’état OPM est indisponible', 'opm.dialog.controlUnreachable': 'Le serveur de contrôle OPM est inaccessible. Cet état signifie indisponible, et non une liste de travail vide.', 'opm.section.needsYou': 'Votre action requise ({count})', 'opm.section.workItems': 'Éléments de travail', 'opm.section.empty': 'Aucun élément de travail en cours.', 'opm.footer.counts': 'Votre action {needsYou} · bloqués {blocked} · en cours {working} · en attente {waiting} · en file {queued}',
} satisfies OpmMessages;

const ja = {
  'opm.phase.planned': '計画済み', 'opm.phase.active': '作業中', 'opm.phase.waitingOwner': 'あなたの対応待ち', 'opm.phase.waiting': '待機中', 'opm.phase.paused': '一時停止', 'opm.phase.blocked': 'ブロック中', 'opm.phase.review': 'レビュー中', 'opm.phase.merged': 'マージ済み', 'opm.phase.deployed': 'デプロイ済み', 'opm.phase.verified': '検証済み', 'opm.phase.completed': '完了', 'opm.phase.cancelled': 'キャンセル済み', 'opm.phase.failed': '失敗', 'opm.phase.idle': '待機',
  'opm.owner.authorize': '対応が必要です。保護された変更を承認するには、下のコマンドを Issue #{ref} に投稿してください。', 'opm.owner.deadLetter': '対応が必要です。繰り返し発生しているエラーを修正し、Issue #{ref} に「/agent resume」とコメントしてください。', 'opm.owner.paused': 'あなたが一時停止しました。続行するには Issue #{ref} に「/agent resume」とコメントしてください。', 'opm.owner.children': '対応は不要です。子項目が完了すると、この親項目も完了します。', 'opm.owner.review': '対応は不要です。OPM がレビューを依頼し、判定後に続行します。', 'opm.owner.checks': '対応は不要です。CI が候補を確認しています。', 'opm.owner.deployment': '対応は不要です。マージ内容をデプロイしています。', 'opm.owner.worker': '対応は不要です。ワーカー枠が空くと作業を開始します。', 'opm.owner.working': '対応は不要です。OPM が作業中です。', 'opm.owner.nextAction': '明確な対応はありません。OPM の指示: {action}', 'opm.owner.none': '現在、対応は不要です。',
  'opm.row.childOf': '#{ref} の子項目', 'opm.row.nextAction': '次: {action}', 'opm.row.branch': 'ブランチ {branch}', 'opm.row.session': 'セッション {session}', 'opm.row.effect': 'エフェクト {kind}: {status}', 'opm.actions.copy': 'コピー', 'opm.actions.copied': 'コピー済み', 'opm.actions.run': '実行', 'opm.actions.running': '送信中…', 'opm.actions.sent': '送信済み ✓', 'opm.actions.openSession': 'セッションを開く', 'opm.actions.enableNotifications': '通知を有効にする',
  'opm.supervisor.title': 'OPM スーパーバイザーの状態', 'opm.supervisor.running': '実行中', 'opm.supervisor.stopped': '停止中', 'opm.supervisor.paused': '一時停止', 'opm.supervisor.lastPoll': '最終ポーリング {age}', 'opm.supervisor.deadLetters': '配信不能: {count}', 'opm.supervisor.blocked': 'ブロック: {count}', 'opm.supervisor.degraded': '機能低下', 'opm.supervisor.rateLimited': 'レート制限中', 'opm.supervisor.healthy': '正常',
  'opm.notification.title': 'OPM があなたの対応を待っています', 'opm.notification.body': '{item}', 'opm.pill.offline': 'OPM オフライン', 'opm.pill.needsYou': 'OPM · 対応が必要 ({count})', 'opm.pill.blocked': 'OPM · ブロック中 ({count})', 'opm.pill.working': 'OPM · 作業中 ({count})', 'opm.pill.waiting': 'OPM · 待機中 ({count})', 'opm.pill.queued': 'OPM · キュー内 ({count})', 'opm.pill.idle': 'OPM · 待機', 'opm.pill.aria': 'OPM の状態を開く',
  'opm.dialog.noSummary': '概要なし', 'opm.dialog.updated': '更新 {age}', 'opm.dialog.unavailable': 'OPM の状態を取得できません', 'opm.dialog.controlUnreachable': 'OPM 制御サーバーに接続できません。これは作業一覧が空なのではなく、利用できない状態です。', 'opm.section.needsYou': '対応が必要 ({count})', 'opm.section.workItems': '作業項目', 'opm.section.empty': '進行中の作業項目はありません。', 'opm.footer.counts': '対応必要 {needsYou} · ブロック {blocked} · 作業中 {working} · 待機中 {waiting} · キュー内 {queued}',
} satisfies OpmMessages;

const ko = {
  'opm.phase.planned': '계획됨', 'opm.phase.active': '작업 중', 'opm.phase.waitingOwner': '사용자 조치 대기', 'opm.phase.waiting': '대기 중', 'opm.phase.paused': '일시 중지됨', 'opm.phase.blocked': '차단됨', 'opm.phase.review': '검토 중', 'opm.phase.merged': '병합됨', 'opm.phase.deployed': '배포됨', 'opm.phase.verified': '검증됨', 'opm.phase.completed': '완료됨', 'opm.phase.cancelled': '취소됨', 'opm.phase.failed': '실패', 'opm.phase.idle': '유휴',
  'opm.owner.authorize': '조치가 필요합니다. 보호된 변경을 승인하려면 아래 명령을 이슈 #{ref}에 게시하세요.', 'opm.owner.deadLetter': '조치가 필요합니다. 반복 실패 원인을 해결한 뒤 이슈 #{ref}에 "/agent resume"을 댓글로 남기세요.', 'opm.owner.paused': '사용자가 일시 중지했습니다. 계속하려면 이슈 #{ref}에 "/agent resume"을 댓글로 남기세요.', 'opm.owner.children': '조치할 필요가 없습니다. 하위 항목이 끝나면 이 상위 항목도 완료됩니다.', 'opm.owner.review': '조치할 필요가 없습니다. OPM이 검토를 요청하고 판정 후 계속합니다.', 'opm.owner.checks': '조치할 필요가 없습니다. CI가 후보를 검사하고 있습니다.', 'opm.owner.deployment': '조치할 필요가 없습니다. 병합 결과를 배포하고 있습니다.', 'opm.owner.worker': '조치할 필요가 없습니다. 작업자 자리가 비면 작업이 시작됩니다.', 'opm.owner.working': '조치할 필요가 없습니다. OPM이 작업 중입니다.', 'opm.owner.nextAction': '명확한 사용자 조치는 없습니다. OPM 안내: {action}', 'opm.owner.none': '지금은 조치할 필요가 없습니다.',
  'opm.row.childOf': '#{ref}의 하위 항목', 'opm.row.nextAction': '다음: {action}', 'opm.row.branch': '브랜치 {branch}', 'opm.row.session': '세션 {session}', 'opm.row.effect': '효과 {kind}: {status}', 'opm.actions.copy': '복사', 'opm.actions.copied': '복사됨', 'opm.actions.run': '실행', 'opm.actions.running': '전송 중…', 'opm.actions.sent': '전송됨 ✓', 'opm.actions.openSession': '세션 열기', 'opm.actions.enableNotifications': '알림 활성화',
  'opm.supervisor.title': 'OPM 감독자 상태', 'opm.supervisor.running': '실행 중', 'opm.supervisor.stopped': '중지됨', 'opm.supervisor.paused': '일시 중지됨', 'opm.supervisor.lastPoll': '마지막 폴링 {age}', 'opm.supervisor.deadLetters': '전달 실패: {count}', 'opm.supervisor.blocked': '차단됨: {count}', 'opm.supervisor.degraded': '성능 저하', 'opm.supervisor.rateLimited': '요청 속도 제한됨', 'opm.supervisor.healthy': '정상',
  'opm.notification.title': 'OPM에 사용자 조치가 필요합니다', 'opm.notification.body': '{item}', 'opm.pill.offline': 'OPM 오프라인', 'opm.pill.needsYou': 'OPM · 조치 필요 ({count})', 'opm.pill.blocked': 'OPM · 차단됨 ({count})', 'opm.pill.working': 'OPM · 작업 중 ({count})', 'opm.pill.waiting': 'OPM · 대기 중 ({count})', 'opm.pill.queued': 'OPM · 대기열 ({count})', 'opm.pill.idle': 'OPM · 유휴', 'opm.pill.aria': 'OPM 상태 열기',
  'opm.dialog.noSummary': '요약 없음', 'opm.dialog.updated': '업데이트 {age}', 'opm.dialog.unavailable': 'OPM 상태를 사용할 수 없습니다', 'opm.dialog.controlUnreachable': 'OPM 제어 서버에 연결할 수 없습니다. 작업 목록이 빈 것이 아니라 사용할 수 없는 상태입니다.', 'opm.section.needsYou': '조치 필요 ({count})', 'opm.section.workItems': '작업 항목', 'opm.section.empty': '진행 중인 작업 항목이 없습니다.', 'opm.footer.counts': '조치 필요 {needsYou} · 차단 {blocked} · 작업 중 {working} · 대기 중 {waiting} · 대기열 {queued}',
} satisfies OpmMessages;

const pl = {
  'opm.phase.planned': 'Zaplanowane', 'opm.phase.active': 'W toku', 'opm.phase.waitingOwner': 'Czeka na Ciebie', 'opm.phase.waiting': 'Oczekuje', 'opm.phase.paused': 'Wstrzymane', 'opm.phase.blocked': 'Zablokowane', 'opm.phase.review': 'W przeglądzie', 'opm.phase.merged': 'Scalone', 'opm.phase.deployed': 'Wdrożone', 'opm.phase.verified': 'Zweryfikowane', 'opm.phase.completed': 'Ukończone', 'opm.phase.cancelled': 'Anulowane', 'opm.phase.failed': 'Niepowodzenie', 'opm.phase.idle': 'Bezczynne',
  'opm.owner.authorize': 'Musisz zareagować. Opublikuj poniższe polecenie w zgłoszeniu #{ref}, aby zatwierdzić chronioną zmianę.', 'opm.owner.deadLetter': 'Musisz zareagować. Napraw powtarzający się błąd, a następnie dodaj komentarz „/agent resume” w zgłoszeniu #{ref}.', 'opm.owner.paused': 'To zadanie zostało wstrzymane przez Ciebie. Dodaj komentarz „/agent resume” w zgłoszeniu #{ref}, aby kontynuować.', 'opm.owner.children': 'Nie musisz nic robić. Ten element nadrzędny zakończy się po ukończeniu elementów podrzędnych.', 'opm.owner.review': 'Nie musisz nic robić. OPM zleca przegląd i kontynuuje po werdykcie.', 'opm.owner.checks': 'Nie musisz nic robić. CI sprawdza kandydata.', 'opm.owner.deployment': 'Nie musisz nic robić. Scalenie jest wdrażane.', 'opm.owner.worker': 'Nie musisz nic robić. Praca rozpocznie się, gdy zwolni się miejsce wykonawcze.', 'opm.owner.working': 'Nie musisz nic robić. OPM nad tym pracuje.', 'opm.owner.nextAction': 'Brak oczywistego działania po Twojej stronie. OPM podaje: {action}', 'opm.owner.none': 'W tej chwili nie musisz nic robić.',
  'opm.row.childOf': 'element podrzędny #{ref}', 'opm.row.nextAction': 'Dalej: {action}', 'opm.row.branch': 'gałąź {branch}', 'opm.row.session': 'sesja {session}', 'opm.row.effect': 'efekt {kind}: {status}', 'opm.actions.copy': 'Kopiuj', 'opm.actions.copied': 'Skopiowano', 'opm.actions.run': 'Uruchom', 'opm.actions.running': 'Wysyłanie…', 'opm.actions.sent': 'Wysłano ✓', 'opm.actions.openSession': 'Otwórz sesję', 'opm.actions.enableNotifications': 'Włącz powiadomienia',
  'opm.supervisor.title': 'Stan nadzorcy OPM', 'opm.supervisor.running': 'Działa', 'opm.supervisor.stopped': 'Zatrzymany', 'opm.supervisor.paused': 'Wstrzymany', 'opm.supervisor.lastPoll': 'Ostatnie odpytywanie {age}', 'opm.supervisor.deadLetters': 'Niedostarczone: {count}', 'opm.supervisor.blocked': 'Zablokowane: {count}', 'opm.supervisor.degraded': 'Obniżona sprawność', 'opm.supervisor.rateLimited': 'Ograniczona częstotliwość', 'opm.supervisor.healthy': 'Sprawny',
  'opm.notification.title': 'OPM wymaga Twojego działania', 'opm.notification.body': '{item}', 'opm.pill.offline': 'OPM offline', 'opm.pill.needsYou': 'OPM · wymaga Ciebie ({count})', 'opm.pill.blocked': 'OPM · zablokowane ({count})', 'opm.pill.working': 'OPM · w toku ({count})', 'opm.pill.waiting': 'OPM · oczekuje ({count})', 'opm.pill.queued': 'OPM · w kolejce ({count})', 'opm.pill.idle': 'OPM · bezczynne', 'opm.pill.aria': 'Otwórz stan OPM',
  'opm.dialog.noSummary': 'Brak podsumowania', 'opm.dialog.updated': 'Zaktualizowano {age}', 'opm.dialog.unavailable': 'Stan OPM jest niedostępny', 'opm.dialog.controlUnreachable': 'Nie można połączyć się z serwerem sterującym OPM. To stan niedostępności, a nie pusta lista zadań.', 'opm.section.needsYou': 'Wymaga Ciebie ({count})', 'opm.section.workItems': 'Elementy pracy', 'opm.section.empty': 'Brak elementów pracy w toku.', 'opm.footer.counts': 'Wymaga Ciebie {needsYou} · zablokowane {blocked} · w toku {working} · oczekuje {waiting} · w kolejce {queued}',
} satisfies OpmMessages;

const ptBR = {
  'opm.phase.planned': 'Planejado', 'opm.phase.active': 'Em andamento', 'opm.phase.waitingOwner': 'Aguardando você', 'opm.phase.waiting': 'Aguardando', 'opm.phase.paused': 'Pausado', 'opm.phase.blocked': 'Bloqueado', 'opm.phase.review': 'Em revisão', 'opm.phase.merged': 'Mesclado', 'opm.phase.deployed': 'Implantado', 'opm.phase.verified': 'Verificado', 'opm.phase.completed': 'Concluído', 'opm.phase.cancelled': 'Cancelado', 'opm.phase.failed': 'Falhou', 'opm.phase.idle': 'Ocioso',
  'opm.owner.authorize': 'Você precisa agir. Publique o comando abaixo na issue #{ref} para aprovar a alteração protegida.', 'opm.owner.deadLetter': 'Você precisa agir. Corrija a falha repetida e depois comente "/agent resume" na issue #{ref}.', 'opm.owner.paused': 'Você pausou este item. Comente "/agent resume" na issue #{ref} para continuar.', 'opm.owner.children': 'Você não precisa fazer nada. Este item pai termina quando os itens filhos terminarem.', 'opm.owner.review': 'Você não precisa fazer nada. O OPM solicita uma revisão e continua após o parecer.', 'opm.owner.checks': 'Você não precisa fazer nada. A CI está verificando o candidato.', 'opm.owner.deployment': 'Você não precisa fazer nada. A mesclagem está sendo implantada.', 'opm.owner.worker': 'Você não precisa fazer nada. O trabalho começa quando uma vaga de execução fica livre.', 'opm.owner.working': 'Você não precisa fazer nada. O OPM está trabalhando nisso.', 'opm.owner.nextAction': 'Não há uma ação clara para você. OPM informa: {action}', 'opm.owner.none': 'Você não precisa fazer nada agora.',
  'opm.row.childOf': 'filho de #{ref}', 'opm.row.nextAction': 'Próximo: {action}', 'opm.row.branch': 'branch {branch}', 'opm.row.session': 'sessão {session}', 'opm.row.effect': 'efeito {kind}: {status}', 'opm.actions.copy': 'Copiar', 'opm.actions.copied': 'Copiado', 'opm.actions.run': 'Executar', 'opm.actions.running': 'Enviando…', 'opm.actions.sent': 'Enviado ✓', 'opm.actions.openSession': 'Abrir sessão', 'opm.actions.enableNotifications': 'Ativar notificações',
  'opm.supervisor.title': 'Status do supervisor OPM', 'opm.supervisor.running': 'Em execução', 'opm.supervisor.stopped': 'Parado', 'opm.supervisor.paused': 'Pausado', 'opm.supervisor.lastPoll': 'Última consulta {age}', 'opm.supervisor.deadLetters': 'Mensagens sem destino: {count}', 'opm.supervisor.blocked': 'Bloqueados: {count}', 'opm.supervisor.degraded': 'Degradado', 'opm.supervisor.rateLimited': 'Taxa limitada', 'opm.supervisor.healthy': 'Saudável',
  'opm.notification.title': 'O OPM precisa da sua ação', 'opm.notification.body': '{item}', 'opm.pill.offline': 'OPM offline', 'opm.pill.needsYou': 'OPM · precisa de você ({count})', 'opm.pill.blocked': 'OPM · bloqueado ({count})', 'opm.pill.working': 'OPM · em andamento ({count})', 'opm.pill.waiting': 'OPM · aguardando ({count})', 'opm.pill.queued': 'OPM · na fila ({count})', 'opm.pill.idle': 'OPM · ocioso', 'opm.pill.aria': 'Abrir status do OPM',
  'opm.dialog.noSummary': 'Sem resumo', 'opm.dialog.updated': 'Atualizado {age}', 'opm.dialog.unavailable': 'O status do OPM não está disponível', 'opm.dialog.controlUnreachable': 'Não foi possível acessar o servidor de controle do OPM. Este é um estado de indisponibilidade, não uma lista de trabalho vazia.', 'opm.section.needsYou': 'Precisa de você ({count})', 'opm.section.workItems': 'Itens de trabalho', 'opm.section.empty': 'Não há itens de trabalho em andamento.', 'opm.footer.counts': 'Precisa de você {needsYou} · bloqueados {blocked} · em andamento {working} · aguardando {waiting} · na fila {queued}',
} satisfies OpmMessages;

const uk = {
  'opm.phase.planned': 'Заплановано', 'opm.phase.active': 'У роботі', 'opm.phase.waitingOwner': 'Очікує на вас', 'opm.phase.waiting': 'Очікує', 'opm.phase.paused': 'Призупинено', 'opm.phase.blocked': 'Заблоковано', 'opm.phase.review': 'На перевірці', 'opm.phase.merged': 'Злито', 'opm.phase.deployed': 'Розгорнуто', 'opm.phase.verified': 'Перевірено', 'opm.phase.completed': 'Завершено', 'opm.phase.cancelled': 'Скасовано', 'opm.phase.failed': 'Помилка', 'opm.phase.idle': 'Бездіяльність',
  'opm.owner.authorize': 'Потрібна ваша дія. Опублікуйте команду нижче в задачі №{ref}, щоб схвалити захищену зміну.', 'opm.owner.deadLetter': 'Потрібна ваша дія. Усуньте повторювану помилку, а потім додайте коментар "/agent resume" у задачі №{ref}.', 'opm.owner.paused': 'Ви призупинили цю задачу. Додайте коментар "/agent resume" у задачі №{ref}, щоб продовжити.', 'opm.owner.children': 'Від вас нічого не потрібно. Ця батьківська задача завершиться після завершення дочірніх задач.', 'opm.owner.review': 'Від вас нічого не потрібно. OPM призначає перевірку й продовжує після висновку.', 'opm.owner.checks': 'Від вас нічого не потрібно. CI перевіряє кандидат.', 'opm.owner.deployment': 'Від вас нічого не потрібно. Злиття розгортається.', 'opm.owner.worker': 'Від вас нічого не потрібно. Робота почнеться, коли звільниться місце виконавця.', 'opm.owner.working': 'Від вас нічого не потрібно. OPM працює над цим.', 'opm.owner.nextAction': 'Очевидної дії від вас немає. OPM повідомляє: {action}', 'opm.owner.none': 'Зараз від вас нічого не потрібно.',
  'opm.row.childOf': 'дочірня до №{ref}', 'opm.row.nextAction': 'Далі: {action}', 'opm.row.branch': 'гілка {branch}', 'opm.row.session': 'сеанс {session}', 'opm.row.effect': 'ефект {kind}: {status}', 'opm.actions.copy': 'Копіювати', 'opm.actions.copied': 'Скопійовано', 'opm.actions.run': 'Виконати', 'opm.actions.running': 'Надсилання…', 'opm.actions.sent': 'Надіслано ✓', 'opm.actions.openSession': 'Відкрити сеанс', 'opm.actions.enableNotifications': 'Увімкнути сповіщення',
  'opm.supervisor.title': 'Стан супервізора OPM', 'opm.supervisor.running': 'Працює', 'opm.supervisor.stopped': 'Зупинено', 'opm.supervisor.paused': 'Призупинено', 'opm.supervisor.lastPoll': 'Останнє опитування {age}', 'opm.supervisor.deadLetters': 'Невдалі повідомлення: {count}', 'opm.supervisor.blocked': 'Заблоковано: {count}', 'opm.supervisor.degraded': 'Погіршений стан', 'opm.supervisor.rateLimited': 'Обмежено частоту', 'opm.supervisor.healthy': 'Справний',
  'opm.notification.title': 'OPM потребує вашої дії', 'opm.notification.body': '{item}', 'opm.pill.offline': 'OPM не в мережі', 'opm.pill.needsYou': 'OPM · потрібні ви ({count})', 'opm.pill.blocked': 'OPM · заблоковано ({count})', 'opm.pill.working': 'OPM · у роботі ({count})', 'opm.pill.waiting': 'OPM · очікує ({count})', 'opm.pill.queued': 'OPM · у черзі ({count})', 'opm.pill.idle': 'OPM · бездіяльність', 'opm.pill.aria': 'Відкрити стан OPM',
  'opm.dialog.noSummary': 'Немає підсумку', 'opm.dialog.updated': 'Оновлено {age}', 'opm.dialog.unavailable': 'Стан OPM недоступний', 'opm.dialog.controlUnreachable': 'Не вдалося зв’язатися із сервером керування OPM. Це стан недоступності, а не порожній список робіт.', 'opm.section.needsYou': 'Потрібні ви ({count})', 'opm.section.workItems': 'Робочі елементи', 'opm.section.empty': 'Немає активних робочих елементів.', 'opm.footer.counts': 'Потрібні ви {needsYou} · заблоковано {blocked} · у роботі {working} · очікує {waiting} · у черзі {queued}',
} satisfies OpmMessages;

const zhCN = {
  'opm.phase.planned': '已计划', 'opm.phase.active': '进行中', 'opm.phase.waitingOwner': '等待你处理', 'opm.phase.waiting': '等待中', 'opm.phase.paused': '已暂停', 'opm.phase.blocked': '已阻塞', 'opm.phase.review': '审核中', 'opm.phase.merged': '已合并', 'opm.phase.deployed': '已部署', 'opm.phase.verified': '已验证', 'opm.phase.completed': '已完成', 'opm.phase.cancelled': '已取消', 'opm.phase.failed': '失败', 'opm.phase.idle': '空闲',
  'opm.owner.authorize': '需要你处理。请在议题 #{ref} 中发布下方命令，以批准受保护的更改。', 'opm.owner.deadLetter': '需要你处理。请修复反复出现的故障，然后在议题 #{ref} 中评论“/agent resume”。', 'opm.owner.paused': '这是你暂停的。请在议题 #{ref} 中评论“/agent resume”以继续。', 'opm.owner.children': '你无需处理。子工作项完成后，此父工作项就会完成。', 'opm.owner.review': '你无需处理。OPM 会安排审核，并在得出结论后继续。', 'opm.owner.checks': '你无需处理。CI 正在检查候选版本。', 'opm.owner.deployment': '你无需处理。合并内容正在部署。', 'opm.owner.worker': '你无需处理。有空闲执行槽位后工作会开始。', 'opm.owner.working': '你无需处理。OPM 正在处理。', 'opm.owner.nextAction': '没有明确需要你执行的操作。OPM 提示：{action}', 'opm.owner.none': '目前你无需处理。',
  'opm.row.childOf': '#{ref} 的子项', 'opm.row.nextAction': '下一步：{action}', 'opm.row.branch': '分支 {branch}', 'opm.row.session': '会话 {session}', 'opm.row.effect': '效果 {kind}：{status}', 'opm.actions.copy': '复制', 'opm.actions.copied': '已复制', 'opm.actions.run': '运行', 'opm.actions.running': '发送中…', 'opm.actions.sent': '已发送 ✓', 'opm.actions.openSession': '打开会话', 'opm.actions.enableNotifications': '启用通知',
  'opm.supervisor.title': 'OPM 监督程序状态', 'opm.supervisor.running': '运行中', 'opm.supervisor.stopped': '已停止', 'opm.supervisor.paused': '已暂停', 'opm.supervisor.lastPoll': '上次轮询 {age}', 'opm.supervisor.deadLetters': '死信：{count}', 'opm.supervisor.blocked': '已阻塞：{count}', 'opm.supervisor.degraded': '性能下降', 'opm.supervisor.rateLimited': '受到速率限制', 'opm.supervisor.healthy': '正常',
  'opm.notification.title': 'OPM 需要你处理', 'opm.notification.body': '{item}', 'opm.pill.offline': 'OPM 离线', 'opm.pill.needsYou': 'OPM · 需要你处理 ({count})', 'opm.pill.blocked': 'OPM · 已阻塞 ({count})', 'opm.pill.working': 'OPM · 进行中 ({count})', 'opm.pill.waiting': 'OPM · 等待中 ({count})', 'opm.pill.queued': 'OPM · 排队中 ({count})', 'opm.pill.idle': 'OPM · 空闲', 'opm.pill.aria': '打开 OPM 状态',
  'opm.dialog.noSummary': '无摘要', 'opm.dialog.updated': '更新于 {age}', 'opm.dialog.unavailable': 'OPM 状态不可用', 'opm.dialog.controlUnreachable': '无法连接 OPM 控制服务器。这表示状态不可用，并不表示工作列表为空。', 'opm.section.needsYou': '需要你处理 ({count})', 'opm.section.workItems': '工作项', 'opm.section.empty': '没有正在处理的工作项。', 'opm.footer.counts': '需要你处理 {needsYou} · 已阻塞 {blocked} · 进行中 {working} · 等待中 {waiting} · 排队中 {queued}',
} satisfies OpmMessages;

const zhTW = {
  'opm.phase.planned': '已規劃', 'opm.phase.active': '進行中', 'opm.phase.waitingOwner': '等待你處理', 'opm.phase.waiting': '等待中', 'opm.phase.paused': '已暫停', 'opm.phase.blocked': '已阻擋', 'opm.phase.review': '審查中', 'opm.phase.merged': '已合併', 'opm.phase.deployed': '已部署', 'opm.phase.verified': '已驗證', 'opm.phase.completed': '已完成', 'opm.phase.cancelled': '已取消', 'opm.phase.failed': '失敗', 'opm.phase.idle': '閒置',
  'opm.owner.authorize': '需要你處理。請在議題 #{ref} 中發布下方命令，以核准受保護的變更。', 'opm.owner.deadLetter': '需要你處理。請修正重複發生的故障，然後在議題 #{ref} 中留言「/agent resume」。', 'opm.owner.paused': '這是你暫停的。請在議題 #{ref} 中留言「/agent resume」以繼續。', 'opm.owner.children': '你不需要處理。子工作項目完成後，此父工作項目就會完成。', 'opm.owner.review': '你不需要處理。OPM 會安排審查，並在得到結論後繼續。', 'opm.owner.checks': '你不需要處理。CI 正在檢查候選版本。', 'opm.owner.deployment': '你不需要處理。合併內容正在部署。', 'opm.owner.worker': '你不需要處理。有空閒執行名額後工作會開始。', 'opm.owner.working': '你不需要處理。OPM 正在處理。', 'opm.owner.nextAction': '沒有明確需要你執行的操作。OPM 提示：{action}', 'opm.owner.none': '目前你不需要處理。',
  'opm.row.childOf': '#{ref} 的子項目', 'opm.row.nextAction': '下一步：{action}', 'opm.row.branch': '分支 {branch}', 'opm.row.session': '工作階段 {session}', 'opm.row.effect': '效果 {kind}：{status}', 'opm.actions.copy': '複製', 'opm.actions.copied': '已複製', 'opm.actions.run': '執行', 'opm.actions.running': '傳送中…', 'opm.actions.sent': '已傳送 ✓', 'opm.actions.openSession': '開啟工作階段', 'opm.actions.enableNotifications': '啟用通知',
  'opm.supervisor.title': 'OPM 監督程式狀態', 'opm.supervisor.running': '執行中', 'opm.supervisor.stopped': '已停止', 'opm.supervisor.paused': '已暫停', 'opm.supervisor.lastPoll': '上次輪詢 {age}', 'opm.supervisor.deadLetters': '無法投遞：{count}', 'opm.supervisor.blocked': '已阻擋：{count}', 'opm.supervisor.degraded': '效能下降', 'opm.supervisor.rateLimited': '受到速率限制', 'opm.supervisor.healthy': '正常',
  'opm.notification.title': 'OPM 需要你處理', 'opm.notification.body': '{item}', 'opm.pill.offline': 'OPM 離線', 'opm.pill.needsYou': 'OPM · 需要你處理 ({count})', 'opm.pill.blocked': 'OPM · 已阻擋 ({count})', 'opm.pill.working': 'OPM · 進行中 ({count})', 'opm.pill.waiting': 'OPM · 等待中 ({count})', 'opm.pill.queued': 'OPM · 排隊中 ({count})', 'opm.pill.idle': 'OPM · 閒置', 'opm.pill.aria': '開啟 OPM 狀態',
  'opm.dialog.noSummary': '沒有摘要', 'opm.dialog.updated': '更新於 {age}', 'opm.dialog.unavailable': 'OPM 狀態無法使用', 'opm.dialog.controlUnreachable': '無法連線 OPM 控制伺服器。這表示狀態無法使用，並不表示工作清單是空的。', 'opm.section.needsYou': '需要你處理 ({count})', 'opm.section.workItems': '工作項目', 'opm.section.empty': '沒有進行中的工作項目。', 'opm.footer.counts': '需要你處理 {needsYou} · 已阻擋 {blocked} · 進行中 {working} · 等待中 {waiting} · 排隊中 {queued}',
} satisfies OpmMessages;

export const opmStatusI18n = {
  en,
  de,
  es,
  fr,
  ja,
  ko,
  pl,
  'pt-BR': ptBR,
  uk,
  'zh-CN': zhCN,
  'zh-TW': zhTW,
};
